import argparse
import zipfile
import numpy as np
from collections import defaultdict

def parse_annotation_file(annotation_fn):
    """
    :param annotation_fn: the gene annotations file
    :return: outputs a list of tuples, "genes". Every tuple represents one gene, the first element of the tuple is the
            list of exon index ranges for that gene, the second element of the tuple is the list of isoforms that exist
            for that gene. For example, genes[0][0][0] references the first exon range of the first gene (in a tuple),
            genes[2][1][3] references the fourth isoform of the third gene.
    """

    with open(annotation_fn, 'r') as aFile:
        N = int(aFile.readline().strip())
        genes = [None]*N
        for i in range(N):
            numExons = int(aFile.readline().strip())
            exons = [None]*numExons
            starts = [int(x) for x in aFile.readline().strip().split(' ')]
            ends = [int(x) for x in aFile.readline().strip().split(' ')]
            for j in range(numExons):
                exons[j] = (starts[j], ends[j])
            numIsoforms = int(aFile.readline().strip())
            isoforms = [None]*numIsoforms
            for j in range(numIsoforms):
                isoforms[j] = [int(x) for x in aFile.readline().strip().split(' ')]
            genes[i] = (exons, isoforms)
    return genes


def parse_genome_file(genome_fn):
    """
    :param genome_fn: the full genome file
    :return: the string containing the genome
    """

    with open(genome_fn, 'r') as gFile:
        return gFile.readline().strip()

def parse_reads_file(reads_fn):
    """
    :param reads_fn: the file of shuffled reads
    :return: a list containing all of the shuffled reads
    """
    
    out_reads = []
    with open(reads_fn, 'r') as rFile:
        for line in rFile:
            out_reads.append(line.strip())
    return out_reads

def direct_align(exons, read):
    aligned = []
    for exon in exons:
        if read in exon:
            aligned.append(exon)
    if aligned:
        return aligned
    return -1

def quantify_isoforms(genes, genome, reads):
    """
    :param genes: the list of gene tuples generated by the parser
    :param genome_fn: the full genome file
    :param reads_fn: the file of shuffled reads
    :return: a list of tuples, where the first element of the tuple is the transcript sequence (the isoform in terms of
            the exon sequences that form it in the genome), and the second element of the tuple is the abundance of that
            specific isoform

            NOTE: this skeleton is built assuming the return value exists like this, but as long as you change the way
            the output file is generated, this can be in whatever form you like.
    """

    """
        TODO: Within this function, you should go through most of the process of quantifying isoforms given the data.
            This can be broken down into the following few steps:
    """
    
    exon_freqs = defaultdict(int)
    exons = []
    exomes = []

    print('aligning to exons...')
    for i in range(len(genes)):
        exons.append([])
        ex = ''
        for indices in genes[i][0]:
            exon = genome[indices[0]:indices[1]+1]
            exons[i].append(exon)
        exomes.append(ex)

    for i in range(len(genes)):
        for read in reads:
            aligned = direct_align(exons[i], read)
            if aligned != -1:
                for exon in aligned:
                    exon_freqs[exon] += 1

    transcriptomes = []
    exon_lengths = []
    exon_counts = []
    isoform_abundance = []

    print('making A and b...')
    for i in range(len(genes)):
        transcriptomes.append([])
        exon_lengths.append([])
        exon_counts.append([])
        counts = []
        for j in range(len(exons[i])):
                counts.append(exon_freqs[exons[i][j]])
        for isoform in genes[i][1]:
            trans = ''
            lengths = [0 for k in range(len(genes[i][0]))]
            for gene_idx in isoform:
                trans += exons[i][gene_idx]
                lengths[gene_idx] = len(exons[i][gene_idx]) - 49
            transcriptomes[i].append(trans)
            exon_lengths[i].append(lengths)
        exon_counts[i] = counts
        A = np.array(exon_lengths[i]).T
        b = np.array(exon_counts[i]).T
        x = np.linalg.lstsq(A,b,rcond=None)[0]
        x = [0 if a < 0 else a for a in x]
        abundance = [c/sum(x) for c in x]
        for c in range(len(abundance)):
            isoform_abundance.append((transcriptomes[i][c], abundance[c]))

    return isoform_abundance


if __name__ == "__main__":
    """
    For an example of how you might call this script to run on the data provided:
    
    Usage: python proj4.py -g full_genome.txt -r shuffled_reads.txt -a DATA_PA_1100_0 -o test.out -t hw4_r_4_chr_1
    """
    parser = argparse.ArgumentParser(description='For now this starter code helps parse the files given, but leaves\n'
                                                 'the actual function that must be implemented empty')
    parser.add_argument('-g', '--genome', required=True, dest='genome_file', help='File containing the full genome')
    parser.add_argument('-r', '--reads', required=True, dest='read_file', help='File containing the shuffled reads')
    parser.add_argument('-a', '--annotation', required=True, dest='annotation_file', help='File containing gene '
                                                                                          'annotations')
    parser.add_argument('-o', '--outputFile', required=True, dest='output_file', help='Output file name')
    parser.add_argument('-t', '--outputHeader', required=True, dest='output_header',
                        help='String that needs to be output on the first line of the output file so that the online\n'
                             'submission system recognizes which leaderboard this file should be submitted to. For\n'
                             'hw4, this will be hw4_r_4_chr_1')

    args = parser.parse_args()
    genome_fn = args.genome_file
    reads_fn = args.read_file
    annotation_fn = args.annotation_file
    output_fn = args.output_file

    genes = parse_annotation_file(annotation_fn)
    genome = parse_genome_file(genome_fn)
    reads = parse_reads_file(reads_fn)

    output = quantify_isoforms(genes, genome, reads)
    with open(output_fn, 'w') as oFile:
        oFile.write('>' + args.output_header + '\n')
        oFile.write('>RNA\n')
        for isoform in output:
            out_str = '{} {}\n'.format(isoform[0], isoform[1])
            oFile.write(out_str)

    zip_fn = output_fn + '.zip'
    with zipfile.ZipFile(zip_fn, 'w') as zFile:
        zFile.write(output_fn)
